apiVersion: v1
kind: Namespace
metadata:
  name: yellowjobs-server-stag

---
apiVersion: v1
kind: Service
metadata:
  name: yellowjobs-server-stag
spec:
  type: NodePort
  selector:
    app: yellowjobs-server-stag
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4000
      targetPort: 4000
      # Optional field
      # the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30016

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellowjobs-server-stag
spec:
  selector:
    matchLabels:
      app: yellowjobs-server-stag
  replicas: 1
  template:
    metadata:
      labels:
        app: yellowjobs-server-stag
    spec:
      containers:
        - name: yellowjobs-server-stag
          image: docker.io/ans29hul/yellowjobs-server-stag:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: yellowjobs-server-stag-env
                  key: MONGO_URI
          ports:
            - containerPort: 4000
              protocol: "TCP"
